In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('/content/sample_data/Meita_BI/Dataset_Missing_Values_Ok.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [21]:
dataset.head(20)

,Asal,Umur,Salary,Purchased
0,Sleman,20.0,72000.0,No
1,Sleman,18.0,48000.0,Yes
2,Bantul,NaN,54000.0,No
3,Sleman,30.0,61000.0,No
4,Bantul,22.0,NaN,Yes
5,Wonosari,35.0,58000.0,Yes
6,Sleman,NaN,52000.0,No
7,Wonosari,48.0,79000.0,Yes
8,Bantul,33.0,83000.0,No
9,Wonosari,40.0,NaN,Yes


In [15]:
print (x)

[[0.0 0.0 0.0 1.0 0.0 20.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 18.0 48000.0]
 [1.0 0.0 0.0 0.0 0.0 28.142857142857142 54000.0]
 [0.0 0.0 0.0 1.0 0.0 30.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 22.0 62066.666666666664]
 [0.0 0.0 0.0 0.0 1.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 28.142857142857142 52000.0]
 [0.0 0.0 0.0 0.0 1.0 48.0 79000.0]
 [1.0 0.0 0.0 0.0 0.0 33.0 83000.0]
 [0.0 0.0 0.0 0.0 1.0 40.0 62066.666666666664]
 [0.0 0.0 1.0 0.0 0.0 31.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 28.142857142857142 52000.0]
 [0.0 0.0 1.0 0.0 0.0 27.0 79000.0]
 [1.0 0.0 0.0 0.0 0.0 20.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 18.0 48000.0]
 [0.0 0.0 0.0 1.0 0.0 28.142857142857142 54000.0]
 [0.0 1.0 0.0 0.0 0.0 30.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 22.0 62066.666666666664]]


In [16]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'No' 'Yes']


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [17]:
print (x)

[[0.0 0.0 0.0 1.0 0.0 20.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 18.0 48000.0]
 [1.0 0.0 0.0 0.0 0.0 28.142857142857142 54000.0]
 [0.0 0.0 0.0 1.0 0.0 30.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 22.0 62066.666666666664]
 [0.0 0.0 0.0 0.0 1.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 28.142857142857142 52000.0]
 [0.0 0.0 0.0 0.0 1.0 48.0 79000.0]
 [1.0 0.0 0.0 0.0 0.0 33.0 83000.0]
 [0.0 0.0 0.0 0.0 1.0 40.0 62066.666666666664]
 [0.0 0.0 1.0 0.0 0.0 31.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 28.142857142857142 52000.0]
 [0.0 0.0 1.0 0.0 0.0 27.0 79000.0]
 [1.0 0.0 0.0 0.0 0.0 20.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 18.0 48000.0]
 [0.0 0.0 0.0 1.0 0.0 28.142857142857142 54000.0]
 [0.0 1.0 0.0 0.0 0.0 30.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 22.0 62066.666666666664]]


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [19]:
print (x)

[[1.0 0.0 0.0 0.0 1.0 0.0 20.0 72000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 18.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 28.142857142857142 54000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 30.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 22.0 62066.666666666664]
 [1.0 0.0 0.0 0.0 0.0 1.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 28.142857142857142 52000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 33.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 40.0 62066.666666666664]
 [1.0 0.0 0.0 1.0 0.0 0.0 31.0 58000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 28.142857142857142 52000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 27.0 79000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 20.0 72000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 18.0 48000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 28.142857142857142 54000.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 30.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 22.0 62066.666666666664]]
